Repository graasp/graasp-ui, pull requests merged in 2022-11, with the labels that each got.

#181 180 change license
  LICENSE
  package.json
Labels: chore

#178 docs(readme): udpate badges and add storybook link in readme
  README.md
Labels: documentation, chore

#183 feat: add auto-resize message listener
  .github/workflows/test.yml
  .gitignore
  rollup.config.js
  src/UserSwitch/UserSwitchWrapper.tsx
  src/items/AppItem.tsx
  src/items/withResizing.tsx
  src/quill-emoji.d.ts
  yarn.lock
Labels: enhancement
