Repository graasp/graasp-ui, pull requests merged in 2023-03, with the labels that each got.

#266 fix: add key to list element in platform switch
  src/PlatformSwitch/PlatformSwitch.tsx
Labels: bug

#270 docs: update license in readme
  README.md
Labels: documentation

#264 fix: set default skeleton variant to circular for Avatar
  src/Avatar/Avatar.tsx
  src/Card/Card.tsx
  src/Card/CardHeader.tsx
  src/items/ItemSkeleton/ItemSkeleton.tsx
Labels: bug

#268 267 improve optional types on itemloginauthorization
  src/Collapse/withCollapse.tsx
  src/itemLogin/ItemLoginAuthorization.tsx
  src/itemLogin/ItemLoginScreen.tsx
  src/items/DocumentItem.tsx
Labels: bug

#241 feat: implement document style flavors
  package.json
  src/TextEditor/TextEditor.tsx
  src/items/DocumentItem.tsx
  yarn.lock
Labels: feature

#274 fix: use MimeTypes and ThumbnailSize from sdk
  package.json
  src/Thumbnail/Thumbnail.tsx
  src/constants.ts
  src/icons/ItemIcon.stories.tsx
  src/icons/ItemIcon.tsx
  src/items/FileAudio.stories.tsx
  src/items/FileItem.stories.tsx
  src/items/FileItem.tsx
  src/items/S3FileItem.tsx
  src/types.ts
  yarn.lock
Labels: chore

#287 Fix operator priority on `FavoriteButton`
  src/buttons/FavoriteButton/FavoriteButton.tsx
Labels: bug

#283 282 display item badges on card
  src/Card/Card.stories.tsx
  src/Card/Card.tsx
  src/ItemBadges/ItemBadges.stories.tsx
  src/ItemBadges/ItemBadges.tsx
  src/ItemBadges/index.ts
  src/TableComponent/Table.stories.tsx
  src/TableComponent/Table.tsx
  src/constants.ts
  src/index.ts
Labels: feature

#279 feat: add header platform colors
  src/Header/Header.stories.tsx
  src/Header/Header.tsx
  src/Main/Main.tsx
  src/theme.ts
Labels: feature

#277 feat: add etherpad logo
  src/icons/EtherpadIcon.stories.tsx
  src/icons/EtherpadIcon.tsx
  src/icons/ItemIcon.tsx
  src/icons/index.ts
Labels: feature

#291 fix: search bar can be compressed and is responsive
  src/SearchInput/SearchInput.stories.tsx
  src/SearchInput/SearchInput.tsx
Labels: improvement

#295 fix: etherpad icon use current color as default
  src/icons/EtherpadIcon.tsx
Labels: bug

#296 fix: use a darker color for itemBadges
  src/ItemBadges/ItemBadges.tsx
Labels: bug

#297 feat: bump @graasp/sdk
  package.json
  yarn.lock
Labels: dependencies

#304 chore: bump sdk to 0.9.3
  package.json
  src/utils/image.ts
  yarn.lock
Labels: chore, dependencies
