Repository graasp/graasp-ui, pull requests merged in 2023-02, with the labels that each got.

#216 feat: add PlatformSwitch component
  example/package.json
  package.json
  src/PlatformSwitch/PlatformSwitch.stories.tsx
  src/PlatformSwitch/PlatformSwitch.tsx
  src/PlatformSwitch/hooks.ts
  src/PlatformSwitch/index.ts
  src/icons/AnalyticsIcon.tsx
  src/icons/BuildIcon.tsx
  src/icons/LibraryIcon.tsx
  src/icons/PlayIcon.tsx
  src/index.ts
  yarn.lock
Labels: enhancement

#224 fix: clear hover state when platform opens in new tab
  src/PlatformSwitch/PlatformSwitch.tsx
Labels: bug

#228 225 update for exporthook pr
  example/README.md
  example/package.json
  example/public/favicon.ico
  example/public/index.html
  example/public/manifest.json
  example/src/App.test.tsx
  example/src/App.tsx
  example/src/index.css
  example/src/index.tsx
  example/src/setupTests.ts
  example/tsconfig.json
  package.json
  src/Authorization/withAuthorization.stories.tsx
  src/Authorization/withAuthorization.tsx
  src/DynamicTreeView/CustomTreeItem.tsx
  src/DynamicTreeView/DynamicTreeView.tsx
  src/HeaderUserInformation/HeaderUserInformation.tsx
  src/ItemFlag/ItemFlagDialog.stories.tsx
  src/ItemFlag/ItemFlagDialog.tsx
  src/TableComponent/Table.tsx
  src/TableComponent/TableToolbar.tsx
  src/UserSwitch/UserSwitch.tsx
  src/UserSwitch/UserSwitchWrapper.tsx
  src/icons/ItemIcon.tsx
  src/itemLogin/ForbiddenContent.stories.tsx
  src/itemLogin/ForbiddenContent.tsx
  src/itemLogin/ForbiddenText.tsx
  src/itemLogin/ItemLoginAuthorization.tsx
  src/itemLogin/ItemLoginScreen.stories.tsx
  src/itemLogin/ItemLoginScreen.tsx
  src/items/AppItem.stories.tsx
  src/items/AppItem.tsx
  src/items/DocumentItem.stories.tsx
  src/items/DocumentItem.tsx
  src/items/FileItem.stories.tsx
  src/items/FileItem.tsx
  src/items/LinkItem.stories.tsx
  src/items/LinkItem.tsx
  src/items/S3FileItem.tsx
  src/items/withCaption.tsx
  src/items/withResizing.tsx
  src/types.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, chore

#245 242 change share button icon
  .storybook/main.js
  .storybook/public/favicon.ico
  package.json
  src/ItemFlag/ItemFlagButton.tsx
  src/TextEditor/TextEditor.tsx
  src/buttons/ChatboxButton/ChatboxButton.tsx
  src/buttons/CopyButton/CopyButton.tsx
  src/buttons/DeleteButton/DeleteButton.tsx
  src/buttons/DownloadButton/DownloadButton.tsx
  src/buttons/EditButton/EditButton.tsx
  src/buttons/FavoriteButton/FavoriteButton.tsx
  src/buttons/LikeButton/LikeButton.tsx
  src/buttons/MoveButton/MoveButton.tsx
  src/buttons/PinButton/PinButton.tsx
  src/buttons/ShareButton/ShareButton.stories.tsx
  src/buttons/ShareButton/ShareButton.tsx
  yarn.lock
Labels: bug, chore

#248 Update sdk to 0.4.1 and yarn to 3.4.1
  .yarn/releases/yarn-3.3.0.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: chore, dependencies

#256 feat: support wav as audio format
  src/constants.ts
  src/items/FileAudio.stories.tsx
  src/items/FileAudio.tsx
  src/items/FileItem.stories.tsx
Labels: feature

#260 257 use buttontypeenum
  src/buttons/DeleteButton/DeleteButton.tsx
  src/buttons/FavoriteButton/FavoriteButton.stories.tsx
  src/buttons/FavoriteButton/FavoriteButton.tsx
  src/buttons/MoveButton/MoveButton.stories.tsx
  src/buttons/MoveButton/MoveButton.tsx
  src/buttons/PinButton/PinButton.stories.tsx
  src/buttons/PinButton/PinButton.tsx
  src/constants.ts
  src/types.ts
Labels: improvement

#259 fix: improve card component and add stories
  src/Card/Card.stories.tsx
  src/Card/Card.tsx
  src/Card/CardHeader.tsx
Labels: improvement
