Repository graasp/graasp-ui, pull requests merged in 2024-08, with the labels that each got.

#965 chore(main): release 4.24.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#980 chore(main): release 4.25.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#983 fix: add disabled color that does not use transparency
  src/theme.ts
Labels: :eyes: visual

#988 chore(main): release 4.26.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#992 fix: add buttonColor hook
  src/index.ts
Labels: bug :beetle:

#994 fix: item login screen input error
  src/itemLogin/ItemLoginScreen.tsx
Labels: bug :beetle:

#1000 fix: select key prop
  src/Select/Select.tsx
Labels: bug :beetle:

#993 chore(main): release 4.26.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1003 fix: use graasp version of stylis to be compatible with esm
  package.json
  src/ThemeContext/ThemeContext.tsx
  yarn.lock
Labels: bug :beetle:, dependencies

#1008 chore(main): release 4.26.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending
