Repository graasp/graasp-ui, pull requests merged in 2024-06, with the labels that each got.

#887 chore: remove duplicated utils
  package.json
  src/DynamicTreeView/CustomTreeItem.tsx
  src/itemLogin/ItemLoginScreen.tsx
  src/itemLogin/utils.test.ts
  src/itemLogin/utils.ts
  src/utils/utils.test.ts
  yarn.lock
Labels: chore

#886 fix: unset height when using dynamic resizing
  src/items/AppItem.tsx
  src/items/withResizing.tsx
Labels: bug :beetle:

#895 fix: remove max-height
  src/items/withResizing.tsx
Labels: bug :beetle:

#904 fix: add timestamp to app url
  src/items/AppItem.stories.tsx
  src/items/AppItem.tsx
Labels: bug :beetle:

#916 fix: add alignment setting
  package.json
  src/Card/components/CardThumbnail.tsx
  src/items/FileImage.tsx
  src/items/FileItem.tsx
  src/items/FileVideo.tsx
  src/items/SizingWrapper.stories.tsx
  src/items/SizingWrapper.tsx
  src/items/withCaption.stories.tsx
  src/items/withCaption.tsx
  src/theme.ts
  yarn.lock
Labels: feature

#919 fix: allow container to take full-width
  package.json
  src/items/FileAudio.tsx
  src/items/FileItem.stories.tsx
  src/items/FileItem.tsx
  src/items/SizingWrapper.tsx
  src/items/withCaption.tsx
  yarn.lock
Labels: feature, chore, :eyes: visual

#923 chore(main): release 4.20.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending
