Repository graasp/graasp-ui, pull requests merged in 2024-07, with the labels that each got.

#925 fix: remove memberId login in itemLogin component
  package.json
  src/constants.ts
  src/itemLogin/ItemLoginAuthorization.tsx
  src/itemLogin/ItemLoginScreen.stories.tsx
  src/itemLogin/ItemLoginScreen.tsx
  src/itemLogin/MemberIdTextField.tsx
  yarn.lock
Labels: bug :beetle:

#930 fix: theme overrides so helper text is not on white background
  src/theme.ts
Labels: :eyes: visual

#926 chore(main): release 4.20.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#934 chore(main): release 4.21.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#948 chore(main): release 4.22.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#963 chore(main): release 4.23.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
