Repository graasp/graasp-ui, pull requests merged in 2024-03, with the labels that each got.

#734 fix: add styles on table to hide aria-description
  src/TableComponent/Table.tsx
Labels: bug :beetle:

#733 feat: update the withCaption stack depending on the desc placement
  package.json
  src/items/FileItem.stories.tsx
  src/items/withCaption.tsx
  yarn.lock
Labels: feature

#748 fix: allow to add a footer under main
  src/Main/Main.stories.tsx
  src/Main/Main.tsx
Labels: improvement

#756 feat(apps): error fallback form
  package.json
  src/appComponents/ErrorFallback.stories.tsx
  src/appComponents/ErrorFallback.tsx
  src/appComponents/index.ts
  src/appComponents/types.ts
  src/apps.ts
  vite.config.ts
Labels: feature
