Repository graasp/graasp-ui, pull requests merged in 2024-04, with the labels that each got.

#787 fix: allow component as card description
  src/Card/Card.tsx
Labels: :eyes: visual

#788 feat(apps): add question label for unifying style in all survey apps
  src/appComponents/QuestionLabel.stories.tsx
  src/appComponents/QuestionLabel.tsx
  src/appComponents/index.ts
  src/apps.ts
Labels: apps :iphone:

#795 fix: reduce font size in theme
  .storybook/global.css
  src/TableComponent/Table.tsx
  src/theme.ts
Labels: bug :beetle:

#800 fix: update type of function used for signout
  src/UserSwitch/UserSwitchWrapper.tsx
Labels: bug :beetle:

#802 fix: update font scale
  src/theme.ts
Labels: chore, :eyes: visual

#805 feat: expose theme options for next
  .storybook/global.css
  .storybook/preview-head.html
  .storybook/public/fonts/Nunito-variable_wght.ttf
  src/Typography/Typography.stories.tsx
  src/theme.ts
Labels: improvement

#811 fix: decrease cclicence tooltip size
  src/CreativeCommons/CreativeCommons.tsx
Labels: improvement

#814 fix: propose general improvements related to player
  src/Collapse/withCollapse.tsx
  src/Main/Main.stories.tsx
  src/Main/Main.tsx
  src/theme.ts
Labels: improvement

#821 fix: visual improvements for the new background
  package.json
  src/Avatar/Avatar.stories.tsx
  src/Avatar/Avatar.tsx
  src/Avatar/index.ts
  src/Card/Card.stories.tsx
  src/Card/Card.tsx
  src/Card/CardHeader.tsx
  src/Card/Cards.stories.tsx
  src/Collapse/Collapse.tsx
  src/CreativeCommons/CreativeCommons.tsx
  src/Navigation/ExtraItemsNavigation.tsx
  src/Navigation/Navigation.stories.tsx
  src/Navigation/Navigation.tsx
  src/Navigation/ParentsNavigation.tsx
  src/SearchInput/SearchInput.tsx
  src/Select/Select.tsx
  src/TableComponent/Table.tsx
  src/buttons/BookmarkButton/BookmarkButton.tsx
  src/constants.ts
  src/index.ts
  src/theme.ts
  yarn.lock
Labels: :eyes: visual

#825 fix: remove margin when there is no label
  src/Select/Select.stories.tsx
  src/Select/Select.tsx
  src/ThemeContext/LanguageSelect.tsx
  src/ThemeContext/ThemeContext.stories.tsx
  src/ThemeContext/ThemeContext.tsx
Labels: :eyes: visual

#830 fix: update alert title
  src/TextDisplay/withFlavor.tsx
Labels: :eyes: visual

#834 fix: playwright install issue
  .github/workflows/test.yml
Labels: bug :beetle:, build :hammer:
