Repository graasp/graasp-ui, pull requests merged in 2024-12, with the labels that each got.

#1135 fix: url crash on non fqdn value
  src/items/LinkItem.tsx
Labels: bug :beetle:

#1139 fix: cookie banner
  src/CookiesBanner/CookiesBanner.stories.tsx
  src/CookiesBanner/CookiesBanner.tsx
Labels: bug :beetle:

#1142 fix: add smooth scroll
  src/theme.ts
Labels: chore

#1136 chore(main): release 5.4.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1143 fix: scroll behavior
  src/theme.ts
Labels: bug :beetle:

#1144 chore(main): release 5.4.6
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1145 chore(main): release 5.4.7
  CHANGELOG.md
  package.json
Labels: autorelease: pending
