Repository graasp/graasp-ui, pull requests merged in 2024-10, with the labels that each got.

#1064 chore(main): release 5.2.1
  CHANGELOG.md
  package.json
  yarn.lock
Labels: autorelease: pending

#1073 fix: update docs
  README.md
Labels: documentation, chore

#1076 fix: children type and umami-tags
  src/Main/Main.stories.tsx
  src/Main/Main.tsx
Labels: bug :beetle:, chore

#1081 fix: show request access on forbidden only
  src/itemLogin/ItemLoginWrapper.stories.tsx
  src/itemLogin/ItemLoginWrapper.tsx
Labels: bug :beetle:

#1082 fix(tests): setup vitest integration with storybook
  .github/workflows/test.yml
  .storybook/main.ts
  .storybook/vitest.setup.ts
  package.json
  src/Card/Cards.stories.tsx
  src/ItemFlag/ItemFlagDialog.stories.tsx
  src/Navigation/Navigation.stories.tsx
  src/UserSwitch/UserSwitch.stories.tsx
  src/UserSwitch/UserSwitch.tsx
  src/itemLogin/ItemLoginScreen.stories.tsx
  src/itemLogin/ItemLoginWrapper.stories.tsx
  src/utils/fixtures.ts
  vite.config.ts
  vitest.config.ts
  vitest.workspace.ts
  yarn.lock
Labels: chore

#1074 chore(main): release 5.2.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1080 feat: add umami for main components
  src/MainMenu/MenuItem/MenuItem.tsx
  src/PlatformSwitch/PlatformSwitch.stories.tsx
  src/PlatformSwitch/PlatformSwitch.tsx
  src/PlatformSwitch/hooks.ts
  src/SearchInput/SearchInput.tsx
  src/UserSwitch/UserSwitch.tsx
  src/UserSwitch/UserSwitchWrapper.tsx
Labels: feature

#1084 chore(main): release 5.3.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1090 fix: add outlined input background color
  src/theme.ts
Labels: bug :beetle:, chore

#1091 fix: footer should use footer html tag
  src/Main/Main.tsx
Labels: bug :beetle:

#1092 chore(main): release 5.3.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1005 feat: add new funtion to translate a username into a unique color
  src/Avatar/Avatar.stories.tsx
  src/Avatar/Avatar.tsx
  src/Avatar/Avatars.stories.tsx
  src/Avatar/stringToColor.test.ts
  src/Avatar/stringToColor.ts
  src/index.ts
  yarn.lock
Labels: feature

#1096 feat: upgrade mui v6
  package.json
  src/Card/Card.tsx
  src/Card/Cards.stories.tsx
  src/TextEditor/TextEditorWrapper.stories.tsx
  src/draggable/DraggingWrapper.tsx
  src/upload/FileDropper/FileDropper.stories.tsx
  src/upload/UploadFileButton/UploadFileButton.stories.tsx
  yarn.lock
Labels: dependencies

#1093 chore(main): release 5.4.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
