Repository graasp/graasp-ui, pull requests merged in 2024-09, with the labels that each got.

#1015 feat: improve audio file support (m4a, AAC, FLAC, OGG)
  .storybook/public/test-assets/sample.aac
  .storybook/public/test-assets/sample.m4a
  .storybook/public/test-assets/sample.mp3
  .storybook/public/test-assets/sample.ogg
  .storybook/public/test-assets/sample.wav
  package.json
  src/items/FileAudio.stories.tsx
  vite.config.ts
  yarn.lock
Labels: feature

#1017 fix: reverse pin icon
  src/buttons/PinButton/PinButton.tsx
Labels: bug :beetle:

#1019 chore(main): release 4.27.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1027 fix!: remove AGGrid and Jest
  package.json
  src/ItemFlag/ItemFlagDialog.stories.tsx
  src/MainMenu/MenuItem/MenuItem.stories.tsx
  src/Navigation/Navigation.stories.tsx
  src/PlatformSwitch/PlatformSwitch.stories.tsx
  src/Select/Select.stories.tsx
  src/TableComponent/DragCellRenderer.tsx
  src/TableComponent/Table.stories.tsx
  src/TableComponent/Table.tsx
  src/TableComponent/TableNoRowsContent.tsx
  src/TableComponent/TableToolbar.tsx
  src/TableComponent/utils.ts
  src/Tree/Breadcrumbs.stories.tsx
  src/Tree/RowMenu.stories.tsx
  src/Tree/RowMenus.stories.tsx
  src/UserSwitch/UserSwitch.stories.tsx
  src/UserSwitch/UserSwitchWrapper.stories.tsx
  src/buttons/BookmarkButton/BookmarkButton.stories.tsx
  src/buttons/ChatboxButton/ChatboxButton.stories.tsx
  src/buttons/DownloadButton/DownloadButton.stories.tsx
  src/buttons/EditButton/EditButton.stories.tsx
  src/buttons/PinButton/PinButton.stories.tsx
  src/buttons/ShareButton/ShareButton.stories.tsx
  src/index.ts
  src/itemLogin/ItemLoginScreen.stories.tsx
  src/items/AppItem.stories.tsx
  src/table.ts
  src/upload/FileDropper/FileDropper.stories.tsx
  src/upload/UploadFileButton/UploadFileButton.stories.tsx
  yarn.lock
Labels: dependencies

#1030 chore(main): release 5.0.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1031 fix: update test images to rely on local files
  .storybook/public/test-assets/big_photo.jpg
  .storybook/public/test-assets/small_photo.jpg
  .storybook/public/test-assets/test.svg
  .storybook/public/test-assets/test.webp
  src/items/FileItem.stories.tsx
Labels: chore

#1033 fix: update eslint config to flatconfig
  .eslintignore
  .eslintrc
  eslint.config.mjs
  package.json
  src/TextEditor/TextEditor.tsx
  src/hooks/useFullscreen.tsx
  src/items/appItemHooks.ts
  yarn.lock
Labels: chore

#1041 fix: move vitest to dev dependency
  package.json
  yarn.lock
Labels: chore

#1050 fix: quill placeholder does not update
  src/TextEditor/TextEditor.stories.tsx
  src/TextEditor/TextEditor.tsx
  src/TextEditor/TextEditorWrapper.stories.tsx
Labels: bug :beetle:

#1016 fix: improve downloadButton
  src/items/DownloadButtonFileItem.stories.tsx
  src/items/DownloadButtonFileItem.tsx
  src/items/FileItem.tsx
Labels: bug :beetle:, :eyes: visual

#1032 chore(main): release 5.0.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1054 chore(main): release 5.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1061 chore(main): release 5.2.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1066 fix: remove usage of `false` in component return
  src/TextDisplay/withFlavor.tsx
Labels: chore
