Repository graasp/graasp-ui, pull requests merged in 2024-05, with the labels that each got.

#846 fix: quick fix rerender of column defs
  src/TableComponent/Table.tsx
Labels: bug :beetle:

#845 fix: overflow on item login screen
  src/itemLogin/ItemLoginScreen.tsx
Labels: bug :beetle:

#856 fix: apply avatar sizing to the avatar component
  src/Avatar/Avatar.tsx
Labels: bug :beetle:

#859 fix(apps): adapt types in ErrorFallback to work with Sentry v8
  src/appComponents/ErrorFallback.stories.tsx
  src/appComponents/ErrorFallback.tsx
  src/appComponents/types.ts
Labels: bug :beetle:, apps :iphone:

#872 feat(apps): add status chips
  package.json
  src/appComponents/index.ts
  src/appComponents/statusChips/RequiredChip.stories.tsx
  src/appComponents/statusChips/RequiredChip.tsx
  src/appComponents/statusChips/SavedChip.stories.tsx
  src/appComponents/statusChips/SavedChip.tsx
  src/appComponents/statusChips/SubmittedChip.stories.tsx
  src/appComponents/statusChips/SubmittedChip.tsx
  src/appComponents/statusChips/types.ts
  src/apps.ts
Labels: feature, apps :iphone:

#854 fix: add link fancy ui
  .storybook/main.ts
  package.json
  src/Authorization/Redirect.stories.tsx
  src/Authorization/withAuthorization.stories.tsx
  src/Card/FolderCard.stories.tsx
  src/Card/FolderCard.tsx
  src/Card/LinkCard.stories.tsx
  src/Card/LinkCard.tsx
  src/Card/components/CardThumbnail.tsx
  src/Card/constants.ts
  src/GraaspLogo/GraaspLogo.stories.tsx
  src/GraaspLogo/GraaspLogo.tsx
  src/Main/LogoHeader.stories.tsx
  src/Main/Main.stories.tsx
  src/MainMenu/MainMenu.stories.tsx
  src/MainMenu/MenuItem/MenuItem.stories.tsx
  src/Navigation/Navigation.stories.tsx
  src/PlatformSwitch/PlatformSwitch.stories.tsx
  src/Thumbnail/Thumbnail.tsx
  src/Tree/RowMenu.tsx
  src/icons/AnalyticsIcon.stories.tsx
  src/icons/BuildIcon.stories.tsx
  src/icons/EtherpadIcon.stories.tsx
  src/icons/EtherpadIcon.tsx
  src/icons/H5PIcon.tsx
  src/icons/ItemIcon.stories.tsx
  src/icons/ItemIcon.tsx
  src/icons/LibraryIcon.stories.tsx
  src/icons/PlayIcon.stories.tsx
  src/icons/ResizingIcon.tsx
  src/index.ts
  src/items/EtherpadItem.tsx
  src/items/FileItem.tsx
  src/items/LinkItem.stories.tsx
  src/items/LinkItem.tsx
  src/items/withCaption.stories.tsx
  src/items/withCaption.tsx
  src/theme.ts
  yarn.lock
Labels: feature

#879 fix: issue with Iframe sizing
  src/itemLogin/MemberIdTextField.tsx
  src/items/LinkItem.tsx
  src/items/withCaption.tsx
  src/items/withResizing.tsx
Labels: bug :beetle:
