Repository graasp/graasp-ui, pull requests merged in 2024-11, with the labels that each got.

#1116 chore(main): release 5.4.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#1121 fix: remove testing library addon and use unified testing package for storybook
  package.json
  src/ItemFlag/ItemFlagDialog.stories.tsx
  src/MainMenu/MenuItem/MenuItem.stories.tsx
  src/Navigation/Navigation.stories.tsx
  src/PlatformSwitch/PlatformSwitch.stories.tsx
  src/Select/Select.stories.tsx
  src/Tree/Breadcrumbs.stories.tsx
  src/Tree/RowMenu.stories.tsx
  src/Tree/RowMenus.stories.tsx
  src/UserSwitch/UserSwitch.stories.tsx
  src/UserSwitch/UserSwitchWrapper.stories.tsx
  src/buttons/BookmarkButton/BookmarkButton.stories.tsx
  src/buttons/ChatboxButton/ChatboxButton.stories.tsx
  src/buttons/DownloadButton/DownloadButton.stories.tsx
  src/buttons/EditButton/EditButton.stories.tsx
  src/buttons/PinButton/PinButton.stories.tsx
  src/buttons/ShareButton/ShareButton.stories.tsx
  src/itemLogin/ItemLoginScreen.stories.tsx
  src/itemLogin/ItemLoginWrapper.stories.tsx
  src/items/AppItem.stories.tsx
  src/upload/FileDropper/FileDropper.stories.tsx
  src/upload/UploadFileButton/UploadFileButton.stories.tsx
  yarn.lock
Labels: chore

#1126 fix: download button colour and loader behaviour
  src/buttons/DownloadButton/DownloadButton.tsx
  src/constants.ts
Labels: bug :beetle:

#1125 fix: cookie buttons
  src/CookiesBanner/CookiesBanner.tsx
  src/Main/Main.stories.tsx
Labels: bug :beetle:, improvement

#1130 chore(main): release 5.4.4
  CHANGELOG.md
  package.json
Labels: autorelease: pending
